### PR TITLE
fix: allow failedTemplate to be empty

### PR DESCRIPTION
**Pull request by soniqua**
Allows `failedTemplate` to be set to `{}` as advertised in [DOCUMENT.md](https://github.com/helm-unittest/helm-unittest/blob/ad4439e1dafcf03ab25c55587f803a8d7889ca3b/DOCUMENT.md?plain=1#L218) and pass schema validation

### CODE REVIEW

**Comment by ivankatliarchuk** [comment]
Is there is a way to write a test that would file? Is this schema used in Vscode or where exactly?

**Comment by soniqua** [comment]
> Is there is a way to write a test that would file? Is this schema used in Vscode or where exactly?

Yes, if I specify the schema in VSCode:
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
...
  - it: ...
    set:
      myValue: "something that causes the template to fail"
    asserts:
      - failedTemplate:
          {}
```

image

**Comment by ivankatliarchuk** [comment]
Got it. Yeah, I'm not using any of these plugins. Need to think how create a unit or integration tests

**Comment by ivankatliarchuk** [comment]
issue https://github.com/helm-unittest/helm-unittest/issues/363

**Pull request merged**
