### PR TITLE
fix: contains document validator fix

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
- Fix for https://github.com/helm-unittest/helm-unittest/issues/227.  Created demo project https://github.com/ik-workshop/helm-unittests-issues/tree/master/issue-337
- Update Makefile to simply local testing
   + `make help` output avaialble makefile commands
   + `make test-docker` executes all tests in container

Screenshot 2024-01-07 at 18 51 58

- Validator `pkg/unittest/validators/contains_document_validator.go` enchanced with logging

The helm itself does not validate where or not template contains `name` or `namespace` as it works with any template e.g. not just k8s manifests. Possibly we should change a message too `fmt.Sprintf("Kind = %s, apiVersion = %s, Name = %s, Namespace = %s",  v.Kind, v.APIVersion, v.Name, v.Namespace),`

- Adding a GitHub Action to run unit tests with every commit would be a great improvement too.
- Not sure how to add a test without failing `TestV3RunnerOkWithOverrideValuesPassedTests&TestV3RunnerOkWithOverrideValuesPassedTests`
```yml
  - it: should contain document
    documentIndex: 0
    release:
      name: my-release
      namespace: default
    asserts:
      - containsDocument:
          kind: Service
          apiVersion: v1
```

### CODE REVIEW

**Comment by ivankatliarchuk** [comment]
Some unit tests are failing on master. Would be nice to have a `github.action` that executes tests on every MR. Its free for open source projects.
Screenshot 2024-01-07 at 19 01 47

**Comment by ivankatliarchuk** [comment]
Test repo https://github.com/ik-workshop/helm-unittests-issues/tree/master/issue-337
Test output
Screenshot 2024-01-07 at 19 17 58

**Comment by ivankatliarchuk** [comment]
Manage to reproduce an issue https://github.com/helm-unittest/helm-unittest/issues/227
Screenshot 2024-01-07 at 14 41 02

**Comment by ivankatliarchuk** [comment]
for the given manifest
```yaml
# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator
  namespace: default
```
and test
```yaml
suite: spark-operator
templates:
  - rbac.yaml
tests:
  - it: Should contain both ClusterRole and ClusterRoleBinding documents
    asserts:
      - containsDocument:
          kind: ClusterRole
          apiVersion: rbac.authorization.k8s.io/v1
      - hasDocuments:
          count: 2
```
The message is

```
 FAIL  spark-operator	issue-268/tests/rbac-test.yaml
	- Should contain both ClusterRole and ClusterRoleBinding documents

		- asserts[0] `containsDocument` fail
			Template:	chart/templates/rbac.yaml
			DocumentIndex:	1
			Expected to contain document:
				Kind = ClusterRole, apiVersion = rbac.authorization.k8s.io/v1, Name = , Namespace =
```
E.g. ` Name = , Namespace =` name and namespace empty. This probably worth to fix in follow up MR.

**Comment by ivankatliarchuk** [comment]
This pull request is not intended to fix https://github.com/helm-unittest/helm-unittest/issues/268. The idea is to keep the request small. I can create a follow-up fix, just the behaviour for `containsDocument` is unclear, where or not it expects all resources in the manifest to to have same `kind,apiVersion,name,namespace` or at least a single resource is exptected. 

problem reproduced https://github.com/ik-workshop/helm-unittests-issues/tree/master/issue-268
Screenshot 2024-01-07 at 19 57 32

**Comment by quintush** [comment]
Added examples, including the test TestV3RunnerOkWithOverrideValuesPassedTests&TestV3RunnerOkWithOverrideValuesPassedTests (these test validate output based on snapshots, which can be updated using `UPDATE_SNAPSHOTS=true go test ./...`

Will resolve the following issues:
- Resolves #205  
- Resolves #227 
- Resolves #268

**Pull request merged**
